/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Yury Misiyuk (https://sketchfab.com/Tim0)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/dog-a89b49b3d9c647a8805d8d5287f47f48
title: Dog
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.91, 12.04, 0.02]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['037_Vray_Material_#32_0'].geometry} material={materials.Material_32} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
